
interface _GlobalComponents {
      'Add1': typeof import("../components/Add1.vue")['default']
    'AllCapitals': typeof import("../components/AllCapitals.vue")['default']
    'AllCountries': typeof import("../components/AllCountries.vue")['default']
    'AllTracks': typeof import("../components/AllTracks.vue")['default']
    'ArticleCard': typeof import("../components/ArticleCard.vue")['default']
    'Button': typeof import("../components/Button.vue")['default']
    'CityCard': typeof import("../components/CityCard.vue")['default']
    'CityLabel': typeof import("../components/CityLabel.vue")['default']
    'CookieBanner': typeof import("../components/CookieBanner.vue")['default']
    'DownloadPopup': typeof import("../components/DownloadPopup.vue")['default']
    'HomeAbout': typeof import("../components/Home/About.vue")['default']
    'HomeDownLoadApp': typeof import("../components/Home/DownLoadApp.vue")['default']
    'HomeHeroSection': typeof import("../components/Home/HeroSection.vue")['default']
    'HomeSwiperSection': typeof import("../components/Home/SwiperSection.vue")['default']
    'Image': typeof import("../components/Image.vue")['default']
    'Logo': typeof import("../components/Logo.vue")['default']
    'MobileHeaderToggle': typeof import("../components/MobileHeaderToggle.vue")['default']
    'Modal': typeof import("../components/Modal.vue")['default']
    'NativePanners': typeof import("../components/NativePanners.vue")['default']
    'NavButtons': typeof import("../components/NavButtons.vue")['default']
    'NavLinks': typeof import("../components/NavLinks.vue")['default']
    'NewPlayListSection': typeof import("../components/NewPlayListSection.vue")['default']
    'OtherTracks': typeof import("../components/OtherTracks.vue")['default']
    'Pagination': typeof import("../components/Pagination.vue")['default']
    'PlayBar': typeof import("../components/PlayBar.vue")['default']
    'PlayControl': typeof import("../components/PlayControl.vue")['default']
    'PlayListCard': typeof import("../components/PlayListCard.vue")['default']
    'PlayListPanner': typeof import("../components/PlayListPanner.vue")['default']
    'PlaylistShare': typeof import("../components/PlaylistShare.vue")['default']
    'PopularArticlesSec': typeof import("../components/PopularArticlesSec.vue")['default']
    'PrayerFeature': typeof import("../components/PrayerFeature.vue")['default']
    'PrayingToday': typeof import("../components/Praying-today.vue")['default']
    'QuranMainSection': typeof import("../components/QuranMainSection.vue")['default']
    'QuranSearchSection': typeof import("../components/QuranSearchSection.vue")['default']
    'Search': typeof import("../components/Search.vue")['default']
    'Table': typeof import("../components/Table.vue")['default']
    'Td': typeof import("../components/Td.vue")['default']
    'Th': typeof import("../components/Th.vue")['default']
    'LangSwitcher': typeof import("../components/langSwitcher.vue")['default']
    'LayoutFooter': typeof import("../components/layout/Footer.vue")['default']
    'LayoutHeader': typeof import("../components/layout/Header.vue")['default']
    'LayoutLeftSideBar': typeof import("../components/layout/LeftSideBar.vue")['default']
    'LayoutRightSideBar': typeof import("../components/layout/RightSideBar.vue")['default']
    'TrackAuthor': typeof import("../components/trackAuthor.vue")['default']
    'TrackCard': typeof import("../components/trackCard.vue")['default']
    'TracksSection': typeof import("../components/tracksSection.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
    'NuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
    'NuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'SwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'Swiper': typeof import("swiper/vue")['Swiper']
    'SwiperSlide': typeof import("swiper/vue")['SwiperSlide']
    'VitePwaManifest': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
    'NuxtPwaManifest': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
    'NuxtPwaAssets': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']
    'PwaAppleImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleImage.vue")['default']
    'PwaAppleSplashScreenImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleSplashScreenImage.vue")['default']
    'PwaFaviconImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaFaviconImage.vue")['default']
    'PwaMaskableImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaMaskableImage.vue")['default']
    'PwaTransparentImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaTransparentImage.vue")['default']
    'SiteLink': typeof import("../node_modules/nuxt-site-config/dist/runtime/nuxt/component/SiteLink.vue")['default']
    'RobotMeta': typeof import("../node_modules/@nuxtjs/robots/dist/runtime/nuxt/components/RobotMeta")['default']
    'OgImage': typeof import("../node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImage")['default']
    'OgImageScreenshot': typeof import("../node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImageScreenshot")['default']
    'SchemaOrgDebug': typeof import("@unhead/schema-org/vue")['SchemaOrgDebug']
    'SchemaOrgArticle': typeof import("@unhead/schema-org/vue")['SchemaOrgArticle']
    'SchemaOrgBreadcrumb': typeof import("@unhead/schema-org/vue")['SchemaOrgBreadcrumb']
    'SchemaOrgComment': typeof import("@unhead/schema-org/vue")['SchemaOrgComment']
    'SchemaOrgEvent': typeof import("@unhead/schema-org/vue")['SchemaOrgEvent']
    'SchemaOrgFoodEstablishment': typeof import("@unhead/schema-org/vue")['SchemaOrgFoodEstablishment']
    'SchemaOrgHowTo': typeof import("@unhead/schema-org/vue")['SchemaOrgHowTo']
    'SchemaOrgImage': typeof import("@unhead/schema-org/vue")['SchemaOrgImage']
    'SchemaOrgJobPosting': typeof import("@unhead/schema-org/vue")['SchemaOrgJobPosting']
    'SchemaOrgLocalBusiness': typeof import("@unhead/schema-org/vue")['SchemaOrgLocalBusiness']
    'SchemaOrgOrganization': typeof import("@unhead/schema-org/vue")['SchemaOrgOrganization']
    'SchemaOrgPerson': typeof import("@unhead/schema-org/vue")['SchemaOrgPerson']
    'SchemaOrgProduct': typeof import("@unhead/schema-org/vue")['SchemaOrgProduct']
    'SchemaOrgQuestion': typeof import("@unhead/schema-org/vue")['SchemaOrgQuestion']
    'SchemaOrgRecipe': typeof import("@unhead/schema-org/vue")['SchemaOrgRecipe']
    'SchemaOrgReview': typeof import("@unhead/schema-org/vue")['SchemaOrgReview']
    'SchemaOrgVideo': typeof import("@unhead/schema-org/vue")['SchemaOrgVideo']
    'SchemaOrgWebPage': typeof import("@unhead/schema-org/vue")['SchemaOrgWebPage']
    'SchemaOrgWebSite': typeof import("@unhead/schema-org/vue")['SchemaOrgWebSite']
    'SchemaOrgMovie': typeof import("@unhead/schema-org/vue")['SchemaOrgMovie']
    'SchemaOrgCourse': typeof import("@unhead/schema-org/vue")['SchemaOrgCourse']
    'SchemaOrgItemList': typeof import("@unhead/schema-org/vue")['SchemaOrgItemList']
    'SchemaOrgBook': typeof import("@unhead/schema-org/vue")['SchemaOrgBook']
    'SchemaOrgSoftwareApp': typeof import("@unhead/schema-org/vue")['SchemaOrgSoftwareApp']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyAdd1': typeof import("../components/Add1.vue")['default']
    'LazyAllCapitals': typeof import("../components/AllCapitals.vue")['default']
    'LazyAllCountries': typeof import("../components/AllCountries.vue")['default']
    'LazyAllTracks': typeof import("../components/AllTracks.vue")['default']
    'LazyArticleCard': typeof import("../components/ArticleCard.vue")['default']
    'LazyButton': typeof import("../components/Button.vue")['default']
    'LazyCityCard': typeof import("../components/CityCard.vue")['default']
    'LazyCityLabel': typeof import("../components/CityLabel.vue")['default']
    'LazyCookieBanner': typeof import("../components/CookieBanner.vue")['default']
    'LazyDownloadPopup': typeof import("../components/DownloadPopup.vue")['default']
    'LazyHomeAbout': typeof import("../components/Home/About.vue")['default']
    'LazyHomeDownLoadApp': typeof import("../components/Home/DownLoadApp.vue")['default']
    'LazyHomeHeroSection': typeof import("../components/Home/HeroSection.vue")['default']
    'LazyHomeSwiperSection': typeof import("../components/Home/SwiperSection.vue")['default']
    'LazyImage': typeof import("../components/Image.vue")['default']
    'LazyLogo': typeof import("../components/Logo.vue")['default']
    'LazyMobileHeaderToggle': typeof import("../components/MobileHeaderToggle.vue")['default']
    'LazyModal': typeof import("../components/Modal.vue")['default']
    'LazyNativePanners': typeof import("../components/NativePanners.vue")['default']
    'LazyNavButtons': typeof import("../components/NavButtons.vue")['default']
    'LazyNavLinks': typeof import("../components/NavLinks.vue")['default']
    'LazyNewPlayListSection': typeof import("../components/NewPlayListSection.vue")['default']
    'LazyOtherTracks': typeof import("../components/OtherTracks.vue")['default']
    'LazyPagination': typeof import("../components/Pagination.vue")['default']
    'LazyPlayBar': typeof import("../components/PlayBar.vue")['default']
    'LazyPlayControl': typeof import("../components/PlayControl.vue")['default']
    'LazyPlayListCard': typeof import("../components/PlayListCard.vue")['default']
    'LazyPlayListPanner': typeof import("../components/PlayListPanner.vue")['default']
    'LazyPlaylistShare': typeof import("../components/PlaylistShare.vue")['default']
    'LazyPopularArticlesSec': typeof import("../components/PopularArticlesSec.vue")['default']
    'LazyPrayerFeature': typeof import("../components/PrayerFeature.vue")['default']
    'LazyPrayingToday': typeof import("../components/Praying-today.vue")['default']
    'LazyQuranMainSection': typeof import("../components/QuranMainSection.vue")['default']
    'LazyQuranSearchSection': typeof import("../components/QuranSearchSection.vue")['default']
    'LazySearch': typeof import("../components/Search.vue")['default']
    'LazyTable': typeof import("../components/Table.vue")['default']
    'LazyTd': typeof import("../components/Td.vue")['default']
    'LazyTh': typeof import("../components/Th.vue")['default']
    'LazyLangSwitcher': typeof import("../components/langSwitcher.vue")['default']
    'LazyLayoutFooter': typeof import("../components/layout/Footer.vue")['default']
    'LazyLayoutHeader': typeof import("../components/layout/Header.vue")['default']
    'LazyLayoutLeftSideBar': typeof import("../components/layout/LeftSideBar.vue")['default']
    'LazyLayoutRightSideBar': typeof import("../components/layout/RightSideBar.vue")['default']
    'LazyTrackAuthor': typeof import("../components/trackAuthor.vue")['default']
    'LazyTrackCard': typeof import("../components/trackCard.vue")['default']
    'LazyTracksSection': typeof import("../components/tracksSection.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
    'LazyNuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
    'LazyNuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'LazySwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'LazySwiper': typeof import("swiper/vue")['Swiper']
    'LazySwiperSlide': typeof import("swiper/vue")['SwiperSlide']
    'LazyVitePwaManifest': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
    'LazyNuxtPwaManifest': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
    'LazyNuxtPwaAssets': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']
    'LazyPwaAppleImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleImage.vue")['default']
    'LazyPwaAppleSplashScreenImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleSplashScreenImage.vue")['default']
    'LazyPwaFaviconImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaFaviconImage.vue")['default']
    'LazyPwaMaskableImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaMaskableImage.vue")['default']
    'LazyPwaTransparentImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaTransparentImage.vue")['default']
    'LazySiteLink': typeof import("../node_modules/nuxt-site-config/dist/runtime/nuxt/component/SiteLink.vue")['default']
    'LazyRobotMeta': typeof import("../node_modules/@nuxtjs/robots/dist/runtime/nuxt/components/RobotMeta")['default']
    'LazyOgImage': typeof import("../node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImage")['default']
    'LazyOgImageScreenshot': typeof import("../node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImageScreenshot")['default']
    'LazySchemaOrgDebug': typeof import("@unhead/schema-org/vue")['SchemaOrgDebug']
    'LazySchemaOrgArticle': typeof import("@unhead/schema-org/vue")['SchemaOrgArticle']
    'LazySchemaOrgBreadcrumb': typeof import("@unhead/schema-org/vue")['SchemaOrgBreadcrumb']
    'LazySchemaOrgComment': typeof import("@unhead/schema-org/vue")['SchemaOrgComment']
    'LazySchemaOrgEvent': typeof import("@unhead/schema-org/vue")['SchemaOrgEvent']
    'LazySchemaOrgFoodEstablishment': typeof import("@unhead/schema-org/vue")['SchemaOrgFoodEstablishment']
    'LazySchemaOrgHowTo': typeof import("@unhead/schema-org/vue")['SchemaOrgHowTo']
    'LazySchemaOrgImage': typeof import("@unhead/schema-org/vue")['SchemaOrgImage']
    'LazySchemaOrgJobPosting': typeof import("@unhead/schema-org/vue")['SchemaOrgJobPosting']
    'LazySchemaOrgLocalBusiness': typeof import("@unhead/schema-org/vue")['SchemaOrgLocalBusiness']
    'LazySchemaOrgOrganization': typeof import("@unhead/schema-org/vue")['SchemaOrgOrganization']
    'LazySchemaOrgPerson': typeof import("@unhead/schema-org/vue")['SchemaOrgPerson']
    'LazySchemaOrgProduct': typeof import("@unhead/schema-org/vue")['SchemaOrgProduct']
    'LazySchemaOrgQuestion': typeof import("@unhead/schema-org/vue")['SchemaOrgQuestion']
    'LazySchemaOrgRecipe': typeof import("@unhead/schema-org/vue")['SchemaOrgRecipe']
    'LazySchemaOrgReview': typeof import("@unhead/schema-org/vue")['SchemaOrgReview']
    'LazySchemaOrgVideo': typeof import("@unhead/schema-org/vue")['SchemaOrgVideo']
    'LazySchemaOrgWebPage': typeof import("@unhead/schema-org/vue")['SchemaOrgWebPage']
    'LazySchemaOrgWebSite': typeof import("@unhead/schema-org/vue")['SchemaOrgWebSite']
    'LazySchemaOrgMovie': typeof import("@unhead/schema-org/vue")['SchemaOrgMovie']
    'LazySchemaOrgCourse': typeof import("@unhead/schema-org/vue")['SchemaOrgCourse']
    'LazySchemaOrgItemList': typeof import("@unhead/schema-org/vue")['SchemaOrgItemList']
    'LazySchemaOrgBook': typeof import("@unhead/schema-org/vue")['SchemaOrgBook']
    'LazySchemaOrgSoftwareApp': typeof import("@unhead/schema-org/vue")['SchemaOrgSoftwareApp']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const Add1: typeof import("../components/Add1.vue")['default']
export const AllCapitals: typeof import("../components/AllCapitals.vue")['default']
export const AllCountries: typeof import("../components/AllCountries.vue")['default']
export const AllTracks: typeof import("../components/AllTracks.vue")['default']
export const ArticleCard: typeof import("../components/ArticleCard.vue")['default']
export const Button: typeof import("../components/Button.vue")['default']
export const CityCard: typeof import("../components/CityCard.vue")['default']
export const CityLabel: typeof import("../components/CityLabel.vue")['default']
export const CookieBanner: typeof import("../components/CookieBanner.vue")['default']
export const DownloadPopup: typeof import("../components/DownloadPopup.vue")['default']
export const HomeAbout: typeof import("../components/Home/About.vue")['default']
export const HomeDownLoadApp: typeof import("../components/Home/DownLoadApp.vue")['default']
export const HomeHeroSection: typeof import("../components/Home/HeroSection.vue")['default']
export const HomeSwiperSection: typeof import("../components/Home/SwiperSection.vue")['default']
export const Image: typeof import("../components/Image.vue")['default']
export const Logo: typeof import("../components/Logo.vue")['default']
export const MobileHeaderToggle: typeof import("../components/MobileHeaderToggle.vue")['default']
export const Modal: typeof import("../components/Modal.vue")['default']
export const NativePanners: typeof import("../components/NativePanners.vue")['default']
export const NavButtons: typeof import("../components/NavButtons.vue")['default']
export const NavLinks: typeof import("../components/NavLinks.vue")['default']
export const NewPlayListSection: typeof import("../components/NewPlayListSection.vue")['default']
export const OtherTracks: typeof import("../components/OtherTracks.vue")['default']
export const Pagination: typeof import("../components/Pagination.vue")['default']
export const PlayBar: typeof import("../components/PlayBar.vue")['default']
export const PlayControl: typeof import("../components/PlayControl.vue")['default']
export const PlayListCard: typeof import("../components/PlayListCard.vue")['default']
export const PlayListPanner: typeof import("../components/PlayListPanner.vue")['default']
export const PlaylistShare: typeof import("../components/PlaylistShare.vue")['default']
export const PopularArticlesSec: typeof import("../components/PopularArticlesSec.vue")['default']
export const PrayerFeature: typeof import("../components/PrayerFeature.vue")['default']
export const PrayingToday: typeof import("../components/Praying-today.vue")['default']
export const QuranMainSection: typeof import("../components/QuranMainSection.vue")['default']
export const QuranSearchSection: typeof import("../components/QuranSearchSection.vue")['default']
export const Search: typeof import("../components/Search.vue")['default']
export const Table: typeof import("../components/Table.vue")['default']
export const Td: typeof import("../components/Td.vue")['default']
export const Th: typeof import("../components/Th.vue")['default']
export const LangSwitcher: typeof import("../components/langSwitcher.vue")['default']
export const LayoutFooter: typeof import("../components/layout/Footer.vue")['default']
export const LayoutHeader: typeof import("../components/layout/Header.vue")['default']
export const LayoutLeftSideBar: typeof import("../components/layout/LeftSideBar.vue")['default']
export const LayoutRightSideBar: typeof import("../components/layout/RightSideBar.vue")['default']
export const TrackAuthor: typeof import("../components/trackAuthor.vue")['default']
export const TrackCard: typeof import("../components/trackCard.vue")['default']
export const TracksSection: typeof import("../components/tracksSection.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
export const NuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const SwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const Swiper: typeof import("swiper/vue")['Swiper']
export const SwiperSlide: typeof import("swiper/vue")['SwiperSlide']
export const VitePwaManifest: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
export const NuxtPwaManifest: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
export const NuxtPwaAssets: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']
export const PwaAppleImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleImage.vue")['default']
export const PwaAppleSplashScreenImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleSplashScreenImage.vue")['default']
export const PwaFaviconImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaFaviconImage.vue")['default']
export const PwaMaskableImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaMaskableImage.vue")['default']
export const PwaTransparentImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaTransparentImage.vue")['default']
export const SiteLink: typeof import("../node_modules/nuxt-site-config/dist/runtime/nuxt/component/SiteLink.vue")['default']
export const RobotMeta: typeof import("../node_modules/@nuxtjs/robots/dist/runtime/nuxt/components/RobotMeta")['default']
export const OgImage: typeof import("../node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImage")['default']
export const OgImageScreenshot: typeof import("../node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImageScreenshot")['default']
export const SchemaOrgDebug: typeof import("@unhead/schema-org/vue")['SchemaOrgDebug']
export const SchemaOrgArticle: typeof import("@unhead/schema-org/vue")['SchemaOrgArticle']
export const SchemaOrgBreadcrumb: typeof import("@unhead/schema-org/vue")['SchemaOrgBreadcrumb']
export const SchemaOrgComment: typeof import("@unhead/schema-org/vue")['SchemaOrgComment']
export const SchemaOrgEvent: typeof import("@unhead/schema-org/vue")['SchemaOrgEvent']
export const SchemaOrgFoodEstablishment: typeof import("@unhead/schema-org/vue")['SchemaOrgFoodEstablishment']
export const SchemaOrgHowTo: typeof import("@unhead/schema-org/vue")['SchemaOrgHowTo']
export const SchemaOrgImage: typeof import("@unhead/schema-org/vue")['SchemaOrgImage']
export const SchemaOrgJobPosting: typeof import("@unhead/schema-org/vue")['SchemaOrgJobPosting']
export const SchemaOrgLocalBusiness: typeof import("@unhead/schema-org/vue")['SchemaOrgLocalBusiness']
export const SchemaOrgOrganization: typeof import("@unhead/schema-org/vue")['SchemaOrgOrganization']
export const SchemaOrgPerson: typeof import("@unhead/schema-org/vue")['SchemaOrgPerson']
export const SchemaOrgProduct: typeof import("@unhead/schema-org/vue")['SchemaOrgProduct']
export const SchemaOrgQuestion: typeof import("@unhead/schema-org/vue")['SchemaOrgQuestion']
export const SchemaOrgRecipe: typeof import("@unhead/schema-org/vue")['SchemaOrgRecipe']
export const SchemaOrgReview: typeof import("@unhead/schema-org/vue")['SchemaOrgReview']
export const SchemaOrgVideo: typeof import("@unhead/schema-org/vue")['SchemaOrgVideo']
export const SchemaOrgWebPage: typeof import("@unhead/schema-org/vue")['SchemaOrgWebPage']
export const SchemaOrgWebSite: typeof import("@unhead/schema-org/vue")['SchemaOrgWebSite']
export const SchemaOrgMovie: typeof import("@unhead/schema-org/vue")['SchemaOrgMovie']
export const SchemaOrgCourse: typeof import("@unhead/schema-org/vue")['SchemaOrgCourse']
export const SchemaOrgItemList: typeof import("@unhead/schema-org/vue")['SchemaOrgItemList']
export const SchemaOrgBook: typeof import("@unhead/schema-org/vue")['SchemaOrgBook']
export const SchemaOrgSoftwareApp: typeof import("@unhead/schema-org/vue")['SchemaOrgSoftwareApp']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyAdd1: typeof import("../components/Add1.vue")['default']
export const LazyAllCapitals: typeof import("../components/AllCapitals.vue")['default']
export const LazyAllCountries: typeof import("../components/AllCountries.vue")['default']
export const LazyAllTracks: typeof import("../components/AllTracks.vue")['default']
export const LazyArticleCard: typeof import("../components/ArticleCard.vue")['default']
export const LazyButton: typeof import("../components/Button.vue")['default']
export const LazyCityCard: typeof import("../components/CityCard.vue")['default']
export const LazyCityLabel: typeof import("../components/CityLabel.vue")['default']
export const LazyCookieBanner: typeof import("../components/CookieBanner.vue")['default']
export const LazyDownloadPopup: typeof import("../components/DownloadPopup.vue")['default']
export const LazyHomeAbout: typeof import("../components/Home/About.vue")['default']
export const LazyHomeDownLoadApp: typeof import("../components/Home/DownLoadApp.vue")['default']
export const LazyHomeHeroSection: typeof import("../components/Home/HeroSection.vue")['default']
export const LazyHomeSwiperSection: typeof import("../components/Home/SwiperSection.vue")['default']
export const LazyImage: typeof import("../components/Image.vue")['default']
export const LazyLogo: typeof import("../components/Logo.vue")['default']
export const LazyMobileHeaderToggle: typeof import("../components/MobileHeaderToggle.vue")['default']
export const LazyModal: typeof import("../components/Modal.vue")['default']
export const LazyNativePanners: typeof import("../components/NativePanners.vue")['default']
export const LazyNavButtons: typeof import("../components/NavButtons.vue")['default']
export const LazyNavLinks: typeof import("../components/NavLinks.vue")['default']
export const LazyNewPlayListSection: typeof import("../components/NewPlayListSection.vue")['default']
export const LazyOtherTracks: typeof import("../components/OtherTracks.vue")['default']
export const LazyPagination: typeof import("../components/Pagination.vue")['default']
export const LazyPlayBar: typeof import("../components/PlayBar.vue")['default']
export const LazyPlayControl: typeof import("../components/PlayControl.vue")['default']
export const LazyPlayListCard: typeof import("../components/PlayListCard.vue")['default']
export const LazyPlayListPanner: typeof import("../components/PlayListPanner.vue")['default']
export const LazyPlaylistShare: typeof import("../components/PlaylistShare.vue")['default']
export const LazyPopularArticlesSec: typeof import("../components/PopularArticlesSec.vue")['default']
export const LazyPrayerFeature: typeof import("../components/PrayerFeature.vue")['default']
export const LazyPrayingToday: typeof import("../components/Praying-today.vue")['default']
export const LazyQuranMainSection: typeof import("../components/QuranMainSection.vue")['default']
export const LazyQuranSearchSection: typeof import("../components/QuranSearchSection.vue")['default']
export const LazySearch: typeof import("../components/Search.vue")['default']
export const LazyTable: typeof import("../components/Table.vue")['default']
export const LazyTd: typeof import("../components/Td.vue")['default']
export const LazyTh: typeof import("../components/Th.vue")['default']
export const LazyLangSwitcher: typeof import("../components/langSwitcher.vue")['default']
export const LazyLayoutFooter: typeof import("../components/layout/Footer.vue")['default']
export const LazyLayoutHeader: typeof import("../components/layout/Header.vue")['default']
export const LazyLayoutLeftSideBar: typeof import("../components/layout/LeftSideBar.vue")['default']
export const LazyLayoutRightSideBar: typeof import("../components/layout/RightSideBar.vue")['default']
export const LazyTrackAuthor: typeof import("../components/trackAuthor.vue")['default']
export const LazyTrackCard: typeof import("../components/trackCard.vue")['default']
export const LazyTracksSection: typeof import("../components/tracksSection.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
export const LazyNuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
export const LazyNuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const LazySwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const LazySwiper: typeof import("swiper/vue")['Swiper']
export const LazySwiperSlide: typeof import("swiper/vue")['SwiperSlide']
export const LazyVitePwaManifest: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
export const LazyNuxtPwaManifest: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
export const LazyNuxtPwaAssets: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']
export const LazyPwaAppleImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleImage.vue")['default']
export const LazyPwaAppleSplashScreenImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleSplashScreenImage.vue")['default']
export const LazyPwaFaviconImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaFaviconImage.vue")['default']
export const LazyPwaMaskableImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaMaskableImage.vue")['default']
export const LazyPwaTransparentImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaTransparentImage.vue")['default']
export const LazySiteLink: typeof import("../node_modules/nuxt-site-config/dist/runtime/nuxt/component/SiteLink.vue")['default']
export const LazyRobotMeta: typeof import("../node_modules/@nuxtjs/robots/dist/runtime/nuxt/components/RobotMeta")['default']
export const LazyOgImage: typeof import("../node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImage")['default']
export const LazyOgImageScreenshot: typeof import("../node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImageScreenshot")['default']
export const LazySchemaOrgDebug: typeof import("@unhead/schema-org/vue")['SchemaOrgDebug']
export const LazySchemaOrgArticle: typeof import("@unhead/schema-org/vue")['SchemaOrgArticle']
export const LazySchemaOrgBreadcrumb: typeof import("@unhead/schema-org/vue")['SchemaOrgBreadcrumb']
export const LazySchemaOrgComment: typeof import("@unhead/schema-org/vue")['SchemaOrgComment']
export const LazySchemaOrgEvent: typeof import("@unhead/schema-org/vue")['SchemaOrgEvent']
export const LazySchemaOrgFoodEstablishment: typeof import("@unhead/schema-org/vue")['SchemaOrgFoodEstablishment']
export const LazySchemaOrgHowTo: typeof import("@unhead/schema-org/vue")['SchemaOrgHowTo']
export const LazySchemaOrgImage: typeof import("@unhead/schema-org/vue")['SchemaOrgImage']
export const LazySchemaOrgJobPosting: typeof import("@unhead/schema-org/vue")['SchemaOrgJobPosting']
export const LazySchemaOrgLocalBusiness: typeof import("@unhead/schema-org/vue")['SchemaOrgLocalBusiness']
export const LazySchemaOrgOrganization: typeof import("@unhead/schema-org/vue")['SchemaOrgOrganization']
export const LazySchemaOrgPerson: typeof import("@unhead/schema-org/vue")['SchemaOrgPerson']
export const LazySchemaOrgProduct: typeof import("@unhead/schema-org/vue")['SchemaOrgProduct']
export const LazySchemaOrgQuestion: typeof import("@unhead/schema-org/vue")['SchemaOrgQuestion']
export const LazySchemaOrgRecipe: typeof import("@unhead/schema-org/vue")['SchemaOrgRecipe']
export const LazySchemaOrgReview: typeof import("@unhead/schema-org/vue")['SchemaOrgReview']
export const LazySchemaOrgVideo: typeof import("@unhead/schema-org/vue")['SchemaOrgVideo']
export const LazySchemaOrgWebPage: typeof import("@unhead/schema-org/vue")['SchemaOrgWebPage']
export const LazySchemaOrgWebSite: typeof import("@unhead/schema-org/vue")['SchemaOrgWebSite']
export const LazySchemaOrgMovie: typeof import("@unhead/schema-org/vue")['SchemaOrgMovie']
export const LazySchemaOrgCourse: typeof import("@unhead/schema-org/vue")['SchemaOrgCourse']
export const LazySchemaOrgItemList: typeof import("@unhead/schema-org/vue")['SchemaOrgItemList']
export const LazySchemaOrgBook: typeof import("@unhead/schema-org/vue")['SchemaOrgBook']
export const LazySchemaOrgSoftwareApp: typeof import("@unhead/schema-org/vue")['SchemaOrgSoftwareApp']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
